liip_imagine:
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~

        card:
            quality: 75
            filters:
                thumbnail: { size: [570, 380], mode: outbound }

        homepage_stage:
            filters:
                thumbnail: { size: [900, 600], mode: outbound }

        recipe_detail:
            filters:
                thumbnail: { size: [1280, 500], mode: outbound }

        category_stage:
            filters:
                thumbnail: { size: [1280, 250], mode: outbound }